2022-05-12 18:44:08.163 [error] <0.523.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.523.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(#{consumer_count => 0,message_count => 3,queue => <<"payments">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2022-05-12 18:44:08.164 [error] <0.520.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.520.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.522.0>, {<<"client 127.0.0.1:49264 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.523.0> exit with reason bad argument in call to erlang:size(#{consumer_count => 0,message_count => 3,queue => <<"payments">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2022-05-12 18:44:08.164 [error] <0.520.0> Supervisor {<0.520.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.14>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.522.0>, {<<"client 127.0.0.1:49264 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.523.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 18:58:13.525 [error] <0.612.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:964 CRASH REPORT Process <0.612.0> with 0 neighbours crashed with reason: bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 964
2022-05-12 18:58:13.526 [error] <0.609.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:964 Supervisor {<0.609.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.611.0>, {<<"client 127.0.0.1:49270 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.612.0> exit with reason bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 964 in context child_terminated
2022-05-12 18:58:13.527 [error] <0.609.0> Supervisor {<0.609.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.611.0>, {<<"client 127.0.0.1:49270 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.612.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 18:58:30.040 [error] <0.636.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 CRASH REPORT Process <0.636.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(#{consumer_count => 0,message_count => 3,queue => <<"payments">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178
2022-05-12 18:58:30.041 [error] <0.633.0>@rabbit_framing_amqp_0_9_1:shortstr_size:178 Supervisor {<0.633.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.635.0>, {<<"client 127.0.0.1:49272 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.636.0> exit with reason bad argument in call to erlang:size(#{consumer_count => 0,message_count => 3,queue => <<"payments">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 178 in context child_terminated
2022-05-12 18:58:30.042 [error] <0.633.0> Supervisor {<0.633.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.18>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.635.0>, {<<"client 127.0.0.1:49272 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.636.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:45:55.912 [error] <0.322.0>@amqp_channel:handle_call:384 gen_server <0.322.0> terminated with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235777.20978>]}, {state,1,<0.311.0>,<0.321.0>,network,{[],[]},false,<0.323.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:45:55.947 [error] <0.322.0>@amqp_channel:handle_call:384 CRASH REPORT Process <0.322.0> with 0 neighbours crashed with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235777.20978>]}, {state,1,<0.311.0>,<0.321.0>,network,{[],[]},false,<0.323.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:45:55.947 [error] <0.320.0>@amqp_channel:handle_call:384 Supervisor {<0.320.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.311.0>, 1, <0.321.0>, {<<"client 127.0.0.1:49344 -> 127.0.0.1:5672">>,1}) at <0.322.0> exit with reason no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235777.20978>]}, {state,1,<0.311.0>,<0.321.0>,network,{[],[]},false,<0.323.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384 in context child_terminated
2022-05-12 21:45:55.949 [error] <0.320.0> Supervisor {<0.320.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.311.0>, 1, <0.321.0>, {<<"client 127.0.0.1:49344 -> 127.0.0.1:5672">>,1}) at <0.322.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:45:55.950 [error] <0.311.0> gen_server <0.311.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2022-05-12 21:45:55.966 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 811
2022-05-12 21:45:55.966 [error] <0.309.0> Supervisor {<0.309.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.310.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.311.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2022-05-12 21:45:55.967 [error] <0.309.0> Supervisor {<0.309.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.310.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:46:20.343 [error] <0.337.0>@amqp_channel:handle_call:384 gen_server <0.337.0> terminated with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235778.21216>]}, {state,1,<0.328.0>,<0.336.0>,network,{[],[]},false,<0.338.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:46:20.345 [error] <0.337.0>@amqp_channel:handle_call:384 CRASH REPORT Process <0.337.0> with 0 neighbours crashed with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235778.21216>]}, {state,1,<0.328.0>,<0.336.0>,network,{[],[]},false,<0.338.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:46:20.346 [error] <0.335.0>@amqp_channel:handle_call:384 Supervisor {<0.335.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.328.0>, 1, <0.336.0>, {<<"client 127.0.0.1:49346 -> 127.0.0.1:5672">>,1}) at <0.337.0> exit with reason no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235778.21216>]}, {state,1,<0.328.0>,<0.336.0>,network,{[],[]},false,<0.338.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384 in context child_terminated
2022-05-12 21:46:20.348 [error] <0.335.0> Supervisor {<0.335.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.328.0>, 1, <0.336.0>, {<<"client 127.0.0.1:49346 -> 127.0.0.1:5672">>,1}) at <0.337.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:46:20.348 [error] <0.328.0> gen_server <0.328.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2022-05-12 21:46:20.351 [error] <0.328.0> CRASH REPORT Process <0.328.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 811
2022-05-12 21:46:20.351 [error] <0.326.0> Supervisor {<0.326.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.328.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2022-05-12 21:46:20.351 [error] <0.326.0> Supervisor {<0.326.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.327.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.328.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:46:43.597 [error] emulator Error in process <0.19661.0> with exit value:
{undef,[{'Elixir.RabbitMQ.Producer',module_info,[compile],[]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',resolve_module_file,2,[{file,"lib/language_server/dialyzer.ex"},{line,440}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer','-add_warnings/2-fun-0-',2,[{file,"lib/language_server/dialyzer.ex"},{line,422}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2396}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',add_warnings,2,[{file,"lib/language_server/dialyzer.ex"},{line,417}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer','-compile/2-fun-6-',7,[{file,"lib/language_server/dialyzer.ex"},{line,387}]},{timer,tc,1,[{file,"timer.erl"},{line,166}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',compile,2,[{file,"lib/language_server/dialyzer.ex"},{line,324}]}]}
2022-05-12 21:46:43.605 [error] <0.121.0>@Elixir.RabbitMQ.Producer:module_info Supervisor {<0.121.0>,'Elixir.ElixirLS.LanguageServer.Dialyzer.Supervisor'} had child 'Elixir.ElixirLS.LanguageServer.Dialyzer' started with 'Elixir.ElixirLS.LanguageServer.Dialyzer':start_link({<0.117.0>,<<"/home/tania/Becarios_bunsan/rabbitmq_tutorials">>}) at <0.122.0> exit with reason call to undefined function 'Elixir.RabbitMQ.Producer':module_info(compile) in context child_terminated
2022-05-12 21:49:00.220 [error] <0.354.0>@amqp_channel:handle_call:384 gen_server <0.354.0> terminated with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235779.20139>]}, {state,1,<0.345.0>,<0.353.0>,network,{[],[]},false,<0.355.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:49:00.220 [error] <0.354.0>@amqp_channel:handle_call:384 CRASH REPORT Process <0.354.0> with 0 neighbours crashed with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235779.20139>]}, {state,1,<0.345.0>,<0.353.0>,network,{[],[]},false,<0.355.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384
2022-05-12 21:49:00.221 [error] <0.352.0>@amqp_channel:handle_call:384 Supervisor {<0.352.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.345.0>, 1, <0.353.0>, {<<"client 127.0.0.1:49350 -> 127.0.0.1:5672">>,1}) at <0.354.0> exit with reason no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.305.0>,[alias|#Ref<0.3263742885.3004235779.20139>]}, {state,1,<0.345.0>,<0.353.0>,network,{[],[]},false,<0.355.0>,none,none,0,true,none,{0,nil},{0,nil},...}) line 384 in context child_terminated
2022-05-12 21:49:00.222 [error] <0.352.0> Supervisor {<0.352.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.345.0>, 1, <0.353.0>, {<<"client 127.0.0.1:49350 -> 127.0.0.1:5672">>,1}) at <0.354.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-12 21:49:00.224 [error] <0.345.0> gen_server <0.345.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2022-05-12 21:49:00.225 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 811
2022-05-12 21:49:00.226 [error] <0.343.0> Supervisor {<0.343.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.344.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.345.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2022-05-12 21:49:00.226 [error] <0.343.0> Supervisor {<0.343.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.344.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.345.0> exit with reason reached_max_restart_intensity in context shutdown
