2022-05-13 11:30:45.883 [error] <0.307.0> gen_server <0.307.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:30:45.908 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:30:45.908 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49482 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:30:45.908 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49482 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:33:42.675 [error] emulator Error in process <0.28747.0> with exit value:
{undef,[{'Elixir.RabbitMQ.Consumer',module_info,[compile],[]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',resolve_module_file,2,[{file,"lib/language_server/dialyzer.ex"},{line,440}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer','-add_warnings/2-fun-0-',2,[{file,"lib/language_server/dialyzer.ex"},{line,422}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2396}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',add_warnings,2,[{file,"lib/language_server/dialyzer.ex"},{line,417}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer','-compile/2-fun-6-',7,[{file,"lib/language_server/dialyzer.ex"},{line,387}]},{timer,tc,1,[{file,"timer.erl"},{line,166}]},{'Elixir.ElixirLS.LanguageServer.Dialyzer',compile,2,[{file,"lib/language_server/dialyzer.ex"},{line,324}]}]}
2022-05-13 11:33:42.677 [error] <0.121.0>@Elixir.RabbitMQ.Consumer:module_info Supervisor {<0.121.0>,'Elixir.ElixirLS.LanguageServer.Dialyzer.Supervisor'} had child 'Elixir.ElixirLS.LanguageServer.Dialyzer' started with 'Elixir.ElixirLS.LanguageServer.Dialyzer':start_link({<0.117.0>,<<"/home/tania/Becarios_bunsan/rabbitmq_tutorials">>}) at <0.19732.0> exit with reason call to undefined function 'Elixir.RabbitMQ.Consumer':module_info(compile) in context child_terminated
2022-05-13 11:37:37.494 [error] <0.307.0> gen_server <0.307.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:37:37.493 [error] <0.316.0> gen_server <0.316.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:37:37.496 [error] <0.323.0> gen_server <0.323.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:37:37.521 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:37:37.522 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:37:37.521 [error] <0.315.0> Supervisor {<0.315.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49480 -> 127.0.0.1:5672">>,1}) at <0.316.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:37:37.523 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:37:37.522 [error] <0.315.0> Supervisor {<0.315.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49480 -> 127.0.0.1:5672">>,1}) at <0.316.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:37:37.523 [error] <0.322.0> Supervisor {<0.322.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49500 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:37:37.523 [error] <0.322.0> Supervisor {<0.322.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49500 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:37:37.523 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49498 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:37:37.523 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49498 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:46:28.603 [error] <0.353.0> gen_server <0.353.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:46:28.603 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:46:28.603 [error] <0.352.0> Supervisor {<0.352.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49506 -> 127.0.0.1:5672">>,1}) at <0.353.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:46:28.604 [error] <0.352.0> Supervisor {<0.352.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49506 -> 127.0.0.1:5672">>,1}) at <0.353.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:50:36.960 [error] <0.393.0> gen_server <0.393.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:50:36.960 [error] <0.393.0> CRASH REPORT Process <0.393.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:50:36.960 [error] <0.392.0> Supervisor {<0.392.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49514 -> 127.0.0.1:5672">>,1}) at <0.393.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:50:36.960 [error] <0.392.0> Supervisor {<0.392.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49514 -> 127.0.0.1:5672">>,1}) at <0.393.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:53:03.256 [error] <0.379.0> gen_server <0.379.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:53:03.257 [error] <0.379.0> CRASH REPORT Process <0.379.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:53:03.257 [error] <0.378.0> Supervisor {<0.378.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49510 -> 127.0.0.1:5672">>,1}) at <0.379.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:53:03.257 [error] <0.378.0> Supervisor {<0.378.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49510 -> 127.0.0.1:5672">>,1}) at <0.379.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:53:03.257 [error] <0.432.0> gen_server <0.432.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:53:03.258 [error] <0.432.0> CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:53:03.258 [error] <0.431.0> Supervisor {<0.431.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49520 -> 127.0.0.1:5672">>,1}) at <0.432.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:53:03.258 [error] <0.431.0> Supervisor {<0.431.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49520 -> 127.0.0.1:5672">>,1}) at <0.432.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:53:23.977 [error] <0.418.0> gen_server <0.418.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:53:23.978 [error] <0.418.0> CRASH REPORT Process <0.418.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:53:23.979 [error] <0.417.0> Supervisor {<0.417.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49516 -> 127.0.0.1:5672">>,1}) at <0.418.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:53:23.979 [error] <0.417.0> Supervisor {<0.417.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49516 -> 127.0.0.1:5672">>,1}) at <0.418.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 11:53:23.981 [error] <0.471.0> gen_server <0.471.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 11:53:23.982 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 11:53:23.982 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49526 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 11:53:23.982 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49526 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:08.834 [error] <0.1216.0>@amqp_channel:handle_call:384 gen_server <0.1216.0> terminated with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.302.0>,[alias|#Ref<0.535599331.2598961154.156224>]}, {state,1,<0.1207.0>,<0.1215.0>,network,{[],[]},false,<0.1217.0>,none,none,0,true,none,{0,nil},{0,...},...}) line 384
2022-05-13 12:00:08.871 [error] <0.1216.0>@amqp_channel:handle_call:384 CRASH REPORT Process <0.1216.0> with 0 neighbours crashed with reason: no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.302.0>,[alias|#Ref<0.535599331.2598961154.156224>]}, {state,1,<0.1207.0>,<0.1215.0>,network,{[],[]},false,<0.1217.0>,none,none,0,true,none,{0,nil},{0,...},...}) line 384
2022-05-13 12:00:08.872 [error] <0.1214.0>@amqp_channel:handle_call:384 Supervisor {<0.1214.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.1207.0>, 1, <0.1215.0>, {<<"client 127.0.0.1:49690 -> 127.0.0.1:5672">>,1}) at <0.1216.0> exit with reason no function clause matching amqp_channel:handle_call({command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}}, {<0.302.0>,[alias|#Ref<0.535599331.2598961154.156224>]}, {state,1,<0.1207.0>,<0.1215.0>,network,{[],[]},false,<0.1217.0>,none,none,0,true,none,{0,nil},{0,...},...}) line 384 in context child_terminated
2022-05-13 12:00:08.872 [error] <0.1214.0> Supervisor {<0.1214.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.1207.0>, 1, <0.1215.0>, {<<"client 127.0.0.1:49690 -> 127.0.0.1:5672">>,1}) at <0.1216.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:08.873 [error] <0.1207.0> gen_server <0.1207.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2022-05-13 12:00:08.882 [error] <0.1207.0> CRASH REPORT Process <0.1207.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 811
2022-05-13 12:00:08.882 [error] <0.1205.0> Supervisor {<0.1205.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1206.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.1207.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2022-05-13 12:00:08.884 [error] <0.1205.0> Supervisor {<0.1205.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1206.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.1207.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.416 [error] <0.529.0> gen_server <0.529.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:00:56.418 [error] <0.316.0> gen_server <0.316.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:00:56.419 [error] <0.415.0> gen_server <0.415.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:00:56.419 [error] <0.501.0> gen_server <0.501.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:00:56.419 [error] <0.515.0> gen_server <0.515.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:00:56.424 [error] <0.515.0> CRASH REPORT Process <0.515.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:00:56.424 [error] <0.529.0> CRASH REPORT Process <0.529.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:00:56.425 [error] <0.514.0> Supervisor {<0.514.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49584 -> 127.0.0.1:5672">>,1}) at <0.515.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:00:56.430 [error] <0.514.0> Supervisor {<0.514.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49584 -> 127.0.0.1:5672">>,1}) at <0.515.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.430 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:00:56.430 [error] <0.415.0> CRASH REPORT Process <0.415.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:00:56.430 [error] <0.528.0> Supervisor {<0.528.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49586 -> 127.0.0.1:5672">>,1}) at <0.529.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:00:56.431 [error] <0.528.0> Supervisor {<0.528.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49586 -> 127.0.0.1:5672">>,1}) at <0.529.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.431 [error] <0.501.0> CRASH REPORT Process <0.501.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:00:56.431 [error] <0.500.0> Supervisor {<0.500.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49582 -> 127.0.0.1:5672">>,1}) at <0.501.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:00:56.431 [error] <0.500.0> Supervisor {<0.500.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49582 -> 127.0.0.1:5672">>,1}) at <0.501.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.431 [error] <0.315.0> Supervisor {<0.315.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49540 -> 127.0.0.1:5672">>,1}) at <0.316.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:00:56.431 [error] <0.315.0> Supervisor {<0.315.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49540 -> 127.0.0.1:5672">>,1}) at <0.316.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.431 [error] <0.414.0> Supervisor {<0.414.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49564 -> 127.0.0.1:5672">>,1}) at <0.415.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:00:56.431 [error] <0.414.0> Supervisor {<0.414.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49564 -> 127.0.0.1:5672">>,1}) at <0.415.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:00:56.432 [error] <0.317.0> gen_server <0.317.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.316.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-hApnOLsmxDOEgpQe4qTYcg">>,8,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:01:24.638 [error] <0.543.0> gen_server <0.543.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:01:24.639 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:01:24.639 [error] <0.542.0> Supervisor {<0.542.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49588 -> 127.0.0.1:5672">>,1}) at <0.543.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:01:24.640 [error] <0.542.0> Supervisor {<0.542.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49588 -> 127.0.0.1:5672">>,1}) at <0.543.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:01:24.644 [error] <0.557.0> gen_server <0.557.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:01:24.644 [error] <0.345.0> gen_server <0.345.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:01:24.644 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:01:24.645 [error] <0.344.0> Supervisor {<0.344.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49550 -> 127.0.0.1:5672">>,1}) at <0.345.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:01:24.645 [error] <0.344.0> Supervisor {<0.344.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49550 -> 127.0.0.1:5672">>,1}) at <0.345.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:01:24.645 [error] <0.330.0> gen_server <0.330.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:01:24.645 [error] <0.330.0> CRASH REPORT Process <0.330.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:01:24.646 [error] <0.329.0> Supervisor {<0.329.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49546 -> 127.0.0.1:5672">>,1}) at <0.330.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:01:24.646 [error] <0.329.0> Supervisor {<0.329.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49546 -> 127.0.0.1:5672">>,1}) at <0.330.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:01:24.646 [error] <0.331.0> gen_server <0.331.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.330.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-IszBmWCHKfxW3kCqyyPXPQ">>,7,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:01:24.646 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:01:24.648 [error] <0.556.0> Supervisor {<0.556.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49590 -> 127.0.0.1:5672">>,1}) at <0.557.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:01:24.648 [error] <0.556.0> Supervisor {<0.556.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49590 -> 127.0.0.1:5672">>,1}) at <0.557.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:01:24.648 [error] <0.558.0> gen_server <0.558.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.557.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-kME0TGQErPSOcKNgH0T7hg">>,3,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:16:54.776 [error] <0.457.0> gen_server <0.457.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:16:54.776 [error] <0.443.0> gen_server <0.443.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:16:54.776 [error] <0.429.0> gen_server <0.429.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:16:54.776 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:16:54.776 [error] <0.429.0> CRASH REPORT Process <0.429.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:16:54.777 [error] <0.456.0> Supervisor {<0.456.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49574 -> 127.0.0.1:5672">>,1}) at <0.457.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:16:54.777 [error] <0.456.0> Supervisor {<0.456.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49574 -> 127.0.0.1:5672">>,1}) at <0.457.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:16:54.777 [error] <0.428.0> Supervisor {<0.428.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49568 -> 127.0.0.1:5672">>,1}) at <0.429.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:16:54.777 [error] <0.471.0> gen_server <0.471.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:16:54.779 [error] <0.428.0> Supervisor {<0.428.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49568 -> 127.0.0.1:5672">>,1}) at <0.429.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:16:54.779 [error] <0.471.0> CRASH REPORT Process <0.471.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:16:54.783 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49576 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:16:54.785 [error] <0.470.0> Supervisor {<0.470.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49576 -> 127.0.0.1:5672">>,1}) at <0.471.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:16:54.785 [error] <0.359.0> gen_server <0.359.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:16:54.785 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:16:54.786 [error] <0.358.0> Supervisor {<0.358.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49552 -> 127.0.0.1:5672">>,1}) at <0.359.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:16:54.786 [error] <0.358.0> Supervisor {<0.358.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49552 -> 127.0.0.1:5672">>,1}) at <0.359.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:16:54.786 [error] <0.443.0> CRASH REPORT Process <0.443.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:16:54.786 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49572 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:16:54.786 [error] <0.442.0> Supervisor {<0.442.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49572 -> 127.0.0.1:5672">>,1}) at <0.443.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.961 [error] <0.387.0> gen_server <0.387.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:22:50.961 [error] <0.373.0> gen_server <0.373.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:22:50.961 [error] <0.387.0> CRASH REPORT Process <0.387.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:22:50.961 [error] <0.487.0> gen_server <0.487.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:22:50.961 [error] <0.373.0> CRASH REPORT Process <0.373.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:22:50.961 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:22:50.961 [error] <0.401.0> gen_server <0.401.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:22:50.962 [error] <0.372.0> Supervisor {<0.372.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49556 -> 127.0.0.1:5672">>,1}) at <0.373.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:22:50.962 [error] <0.401.0> CRASH REPORT Process <0.401.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:22:50.962 [error] <0.372.0> Supervisor {<0.372.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49556 -> 127.0.0.1:5672">>,1}) at <0.373.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.963 [error] <0.386.0> Supervisor {<0.386.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49560 -> 127.0.0.1:5672">>,1}) at <0.387.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:22:50.963 [error] <0.374.0> gen_server <0.374.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.373.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-9ba8F6UzoVDVI1BXnv2P5A">>,5,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:22:50.963 [error] <0.386.0> Supervisor {<0.386.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49560 -> 127.0.0.1:5672">>,1}) at <0.387.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.963 [error] <0.486.0> Supervisor {<0.486.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49578 -> 127.0.0.1:5672">>,1}) at <0.487.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:22:50.963 [error] <0.400.0> Supervisor {<0.400.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49562 -> 127.0.0.1:5672">>,1}) at <0.401.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:22:50.963 [error] <0.400.0> Supervisor {<0.400.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49562 -> 127.0.0.1:5672">>,1}) at <0.401.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.964 [error] <0.486.0> Supervisor {<0.486.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49578 -> 127.0.0.1:5672">>,1}) at <0.487.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.964 [error] <0.388.0> gen_server <0.388.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.387.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-lEnhwrT-UflGwlRrznrh2g">>,5,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:22:50.964 [error] <0.488.0> gen_server <0.488.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.487.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-KBtxxzBzZa0prCCYh8uFtw">>,4,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:22:50.964 [error] <0.402.0> gen_server <0.402.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.401.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-EnFbp9BJcDFu3uktiMqwOg">>,5,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
2022-05-13 12:22:50.966 [error] <0.584.0> gen_server <0.584.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-05-13 12:22:50.966 [error] <0.584.0> CRASH REPORT Process <0.584.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-05-13 12:22:50.967 [error] <0.583.0> Supervisor {<0.583.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49596 -> 127.0.0.1:5672">>,1}) at <0.584.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-05-13 12:22:50.967 [error] <0.583.0> Supervisor {<0.583.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49596 -> 127.0.0.1:5672">>,1}) at <0.584.0> exit with reason reached_max_restart_intensity in context shutdown
2022-05-13 12:22:50.967 [error] <0.585.0> gen_server <0.585.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.584.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-ng7Zcae_6habiI9kCD3Vcg">>,1,false,<<"bunsan">>,<<"orders">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"hello_police">>}},70000]}} in gen_server2:call/3 line 346
